# DO NOT COMMIT
mining_address_email: "slovacus@gmail.com"
mining_address_eth: "0x2b7Cc08C4E454fE8DB88a9FCA2cCBe27Ee8879b2"


mining_bcn_xmr_minergate_service: True
mining_bcn_xmr_minergate_service_start: True

