---

- name: Common stuff for all the server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - contrib/labpositiva.ntp
    - contrib/hadenlabs.common
  tags:
    - all
    - common
    - provision
    - sync

- name: Mining
  hosts: webservers
  become: true
  roles:
    - contrib/hadenlabs.common
    - mining
  tags:
    - mining
